In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data_NE\pair_1_2001_2005_to_2006_2010.csv')
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\Dell\AppData\Local\Temp\ipykernel_6652\3255982061.py:1: SyntaxWarning: invalid escape sequence '\p'
  df = pd.read_csv('data_NE\pair_1_2001_2005_to_2006_2010.csv')

,system:index,loss_label,past_loss,rainfall_anomaly,rainfall_total,spi,treecover2000,.geo
0,0,1,0,1406.292159,11466.173206,0.681355,32,"{""type"":""Point"",""coordinates"":[92.410081655011..."
1,1,0,0,1309.242957,12575.646368,0.484411,60,"{""type"":""Point"",""coordinates"":[92.857240164650..."
2,2,0,0,2298.527793,16032.454336,0.694143,60,"{""type"":""Point"",""coordinates"":[92.995399227652..."
3,6,0,0,1498.822905,14589.982834,0.532049,90,"{""type"":""Point"",""coordinates"":[92.418345660299..."
4,10,0,0,583.675904,7704.975117,0.366913,68,"{""type"":""Point"",""coordinates"":[94.244158672281..."

In [3]:
df.columns

Index(['system:index', 'loss_label', 'past_loss', 'rainfall_anomaly',
       'rainfall_total', 'spi', 'treecover2000', '.geo'],
      dtype='object')

In [4]:
df.isnull().sum()

system:index        0
loss_label          0
past_loss           0
rainfall_anomaly    0
rainfall_total      0
spi                 0
treecover2000       0
.geo                0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.dtypes

system:index          int64
loss_label            int64
past_loss             int64
rainfall_anomaly    float64
rainfall_total      float64
spi                 float64
treecover2000         int64
.geo                 object
dtype: object

In [6]:
df.describe()

,system:index,loss_label,past_loss,rainfall_anomaly,rainfall_total,spi,treecover2000
count,2715.000000,2715.000000,2715.000000,2715.000000,2715.000000,2715.000000,2715.000000
mean,2491.916759,0.158748,0.025046,1479.326907,12148.957453,0.635762,68.749171
std,1441.395135,0.365508,0.156294,555.489984,3393.087808,0.153230,18.290461
min,0.000000,0.000000,0.000000,110.344061,1748.132816,0.082713,25.000000
25%,1229.500000,0.000000,0.000000,1056.389255,9755.010791,0.540769,56.500000
50%,2486.000000,0.000000,0.000000,1392.104751,12048.509745,0.633386,73.000000
75%,3729.500000,0.000000,0.000000,1858.971726,14320.522694,0.725141,84.000000
max,4998.000000,1.000000,1.000000,3413.271345,23713.491768,1.165792,98.000000

In [7]:
df.shape

(2715, 8)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2715 entries, 0 to 2714
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   system:index      2715 non-null   int64
 1   loss_label        2715 non-null   int64
 2   past_loss         2715 non-null   int64
 3   rainfall_anomaly  2715 non-null   float64
 4   rainfall_total    2715 non-null   float64
 5   spi               2715 non-null   float64
 6   treecover2000     2715 non-null   int64
 7   .geo              2715 non-null   object
dtypes: float64(3), int64(4), object(1)
memory usage: 169.8+ KB