In [14]:
import pandas as pd

In [15]:
df = pd.read_csv('data\pair_1_2001_2005_to_2006_2010.csv')
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\Dell\AppData\Local\Temp\ipykernel_21240\420387440.py:1: SyntaxWarning: invalid escape sequence '\p'
  df = pd.read_csv('data\pair_1_2001_2005_to_2006_2010.csv')

,system:index,loss_label,past_loss,rainfall_anomaly,rainfall_total,spi,treecover2000,.geo
0,14,0,0,-107.147458,2584.798785,-0.181060,80,"{""type"":""Point"",""coordinates"":[74.592781576148..."
1,17,0,0,1545.773129,17677.916177,0.532492,89,"{""type"":""Point"",""coordinates"":[95.235033333574..."
2,22,0,0,-1135.950818,12346.212960,-0.453471,48,"{""type"":""Point"",""coordinates"":[74.180165792698..."
3,34,0,0,763.418267,6565.432127,0.640919,25,"{""type"":""Point"",""coordinates"":[80.726976207340..."
4,44,0,0,2457.079142,15353.112629,0.768016,39,"{""type"":""Point"",""coordinates"":[90.501479177620..."

In [16]:
df.columns

Index(['system:index', 'loss_label', 'past_loss', 'rainfall_anomaly',
       'rainfall_total', 'spi', 'treecover2000', '.geo'],
      dtype='object')

In [17]:
df.isnull().sum()

system:index        0
loss_label          0
past_loss           0
rainfall_anomaly    0
rainfall_total      0
spi                 0
treecover2000       0
.geo                0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.dtypes

system:index          int64
loss_label            int64
past_loss             int64
rainfall_anomaly    float64
rainfall_total      float64
spi                 float64
treecover2000         int64
.geo                 object
dtype: object

In [20]:
df.describe()

,system:index,loss_label,past_loss,rainfall_anomaly,rainfall_total,spi,treecover2000
count,455.000000,455.000000,455.000000,455.000000,455.000000,455.000000,455.000000
mean,2566.312088,0.175824,0.021978,698.489603,10584.930859,0.317429,59.503297
std,1469.676844,0.381090,0.146773,1160.614924,4130.396772,0.514634,20.644129
min,14.000000,0.000000,0.000000,-3894.824192,1199.482079,-1.528556,25.000000
25%,1240.000000,0.000000,0.000000,179.840936,7653.629114,0.107942,43.000000
50%,2708.000000,0.000000,0.000000,822.937360,10484.617346,0.470365,59.000000
75%,3859.500000,0.000000,0.000000,1374.767597,13618.309192,0.641215,78.000000
max,4986.000000,1.000000,1.000000,3461.968274,22029.618906,1.187595,98.000000

In [21]:
df.shape

(455, 8)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 455 entries, 0 to 454
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   system:index      455 non-null    int64
 1   loss_label        455 non-null    int64
 2   past_loss         455 non-null    int64
 3   rainfall_anomaly  455 non-null    float64
 4   rainfall_total    455 non-null    float64
 5   spi               455 non-null    float64
 6   treecover2000     455 non-null    int64
 7   .geo              455 non-null    object
dtypes: float64(3), int64(4), object(1)
memory usage: 28.6+ KB